- name: Pull the github-runner
  community.docker.docker_image:
    name: chandralekhas/github-runner:latest
    source: pull

- name: Get runner  token
  ansible.builtin.shell: |
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"   /orgs/azure-prep/actions/runners/registration-token | jq .token | xargs
  delegate_to: localhost
  register: github_token

- name: Deploy runner
  community.docker.docker_container:
    name: "{{ item }}"
    image: chandralekhas/github-runner:latest
    env:
      TOKEN: "{{ github_token }}"
      NAME: "{{ item }}"
      ARM_CLIENT_ID:  "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_ID token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      ARM_CLIENT_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_SECRET token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      ARM_SUBSCRIPTION_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_SUBSCRIPTION_ID token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      ARM_TENANT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_TENANT_ID token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
    state: started
  loop:
    - runner1
    - runner2
    - runner3