- name: Pull the github-runner
  community.docker.docker_image:
    name: chandralekhas/github-runner:latest
    source: pull

- name: Get runner  token
  ansible.builtin.shell: |
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"   /orgs/azure-prep/actions/runners/registration-token | jq .token | xargs
  delegate_to: localhost
  become: false
  register: github_token

- name: Print runner token
  ansible.builtin.debug:
    msg: "{{ github_token.stdout }}"

- name: Template a file to /usr/lib/systemd/system/docker.service
  become: yes
  ansible.builtin.template:
    src: docker.service
    dest: /usr/lib/systemd/system/docker.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Deploy runner
  community.docker.docker_container:
    name: "{{ item }}"
    pull: true
    recreate: true
    image: chandralekhas/github-runner:latest
    env:
      TOKEN: "{{ github_token.stdout }}"
      NAME: "{{ item }}"
      ARM_CLIENT_ID:  "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_ID token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      ARM_CLIENT_SECRET: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_CLIENT_SECRET token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      ARM_SUBSCRIPTION_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_SUBSCRIPTION_ID token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      ARM_TENANT_ID: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/azure-sp:ARM_TENANT_ID token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  loop:
    - runner1
    - runner2
    - runner3