- name: Pull the github-runner
  community.docker.docker_image:
    name: chandralekhas/github-runner:latest
    source: pull

- name: Deploy runner
  community.docker.docker_container:
    name: github-runner
    image: chandralekhas/github-runner:latest
    env:
      # Define key-value pairs for environment variables
      TOKEN: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-infra/data/github:token token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      NAME: "runner-dev-1"
    state: started
