- name: copy repo
  ansible.builtin.get_url:
    url: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: copy file
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start the service.
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: "{{ component }}"