- name: Download repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: installed

- name: Copy vault config
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: Start Vault service
  ansible.builtin.systemd_service:
    name: vault
    state: started
    enabled: yes

- name: Install Vault
  ansible.builtin.dnf:
    name: jq
    state: installed

- name: Initialize Vault if not already initialized
  ansible.builtin.shell: |
    export VAULT_ADDR="http://vault-int.azdevopsb1.online:8200"
    if ! vault status -format=json | jq -e '.initialized' >/dev/null; then
      vault operator init -key-shares=1 -key-threshold=1 -format=json > vault-keys.json
      cat vault-keys.json
      vault operator unseal "$(jq -r '.unseal_keys_b64[0]' vault-keys.json)"
      echo "VAULT_ROOT_TOKEN=$(jq -r '.root_token' vault-keys.json)"
    else
      echo "Vault already initialized"
    fi
  register: vault_init_output
  changed_when: false

- name: Print Vault root token
  ansible.builtin.debug:
    msg: "{{ vault_init_output.stdout_lines }}"