- name: copy repo
  ansible.builtin.get_url:
    url: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    dest: /etc/yum.repos.d/vault.repo

- name: Install vault
  ansible.builtin.dnf:
    name: vault


