- name: Install kubectl
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Update package cache
  ansible.builtin.package:
    update_cache: true
    state: present

- name: Install kubectl Docker
  ansible.builtin.shell: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes


- name: Install k9s
  ansible.builtin.dnf:
    name: https://github.com/derailed/k9s/releases/download/v0.50.16/k9s_linux_amd64.rpm
    state: present
    disable_yum_gpg_check: true

